In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#df = pd.read_csv('final_dataset_wo_duplicates.csv')
df = pd.read_csv('travel_destinations.csv')
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                                  Tags  \
0                        Historical & Heritage |  City   
1                        City |  Historical & Heritage   
2                                                 City   
3                                           Pilgrimage   
4                                         Hill Station   
5                                           Pilgrimage   
6                                         Hill Station   
7                        Historical & Heritage |  City   
8                                   Pilgrimage |  City   
9                                                Beach   
10                                        Hill Station   
11                                          Pilgrimage   
12                                        Hill Station   
13                           Beach |  Lake & Backwater   
14                                          Pilgrimage   
15                               Historical & Heritage   
16                                        Hill Station   
17                 Historical & Heritage |  Pilgrimage   
18                                        Hill Station   
19                                          Pilgrimage   
20                                       Beach |  City   
21                       Historical & Heritage |  City   
22                  Pilgrimage |  Adventure / Trekking   
23                                 Beach |  Pilgrimage   
24                       Historical & Heritage |  City   
25                               Historical & Heritage   
26                                    Lake & Backwater   
27         Historical & Heritage |  Pilgrimage |  City   
28                                        Hill Station   
29                               Historical & Heritage 

# Create index_destination_dict

In [3]:
index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict

{0: 'Delhi City',
 1: 'Agra',
 2: 'Panjim',
 3: 'Varanasi',
 4: 'Shimla',
 5: 'Haridwar',
 6: 'Ooty',
 7: 'Jaipur',
 8: 'Tirupati',
 9: 'Andaman Islands',
 10: 'Munnar',
 11: 'Shirdi',
 12: 'Manali',
 13: 'Alleppey',
 14: 'Somnath',
 15: 'Ajanta Caves',
 16: 'Nainital',
 17: 'Amritsar',
 18: 'Darjeeling',
 19: 'Rameshwaram',
 20: 'Pondicherry',
 21: 'Mysore',
 22: 'Rishikesh',
 23: 'Puri',
 24: 'Mumbai',
 25: 'Hampi',
 26: 'Kumarakom',
 27: 'Madurai',
 28: 'Coorg',
 29: 'Udaipur',
 30: 'Kanchipuram',
 31: 'Jim Corbett National Park',
 32: 'Mussoorie',
 33: 'Hyderabad',
 34: 'Mahabaleshwar',
 35: 'Kovalam',
 36: 'Jodhpur',
 37: 'Ahmedabad',
 38: 'Kodaikanal',
 39: 'Thekkady',
 40: 'Khajuraho',
 41: 'Kaziranga National Park',
 42: 'Chikmagalur',
 43: 'Sabarimala',
 44: 'Konark',
 45: 'Gir National Park',
 46: 'Mahabalipuram',
 47: 'Gangtok',
 48: 'Jaisalmer',
 49: 'Bandhavgarh National Park',
 50: 'Athirapally Waterfalls',
 51: 'Wayanad',
 52: 'Nagarhole National Park',
 53: 'Kanyakumari

# Create destination_index_dict

In [4]:
destination_index_dict = {}
for i in range(len(df)):
    destination_index_dict[df.loc[i]['City']] = i
destination_index_dict

{'Delhi City': 0,
 'Agra': 1,
 'Panjim': 2,
 'Varanasi': 3,
 'Shimla': 4,
 'Haridwar': 5,
 'Ooty': 6,
 'Jaipur': 7,
 'Tirupati': 8,
 'Andaman Islands': 9,
 'Munnar': 10,
 'Shirdi': 11,
 'Manali': 12,
 'Alleppey': 13,
 'Somnath': 14,
 'Ajanta Caves': 15,
 'Nainital': 16,
 'Amritsar': 17,
 'Darjeeling': 18,
 'Rameshwaram': 19,
 'Pondicherry': 20,
 'Mysore': 21,
 'Rishikesh': 22,
 'Puri': 23,
 'Mumbai': 24,
 'Hampi': 25,
 'Kumarakom': 26,
 'Madurai': 27,
 'Coorg': 28,
 'Udaipur': 29,
 'Kanchipuram': 30,
 'Jim Corbett National Park': 31,
 'Mussoorie': 32,
 'Hyderabad': 33,
 'Mahabaleshwar': 34,
 'Kovalam': 35,
 'Jodhpur': 36,
 'Ahmedabad': 37,
 'Kodaikanal': 38,
 'Thekkady': 39,
 'Khajuraho': 40,
 'Kaziranga National Park': 41,
 'Chikmagalur': 42,
 'Sabarimala': 43,
 'Konark': 44,
 'Gir National Park': 45,
 'Mahabalipuram': 46,
 'Gangtok': 47,
 'Jaisalmer': 48,
 'Bandhavgarh National Park': 49,
 'Athirapally Waterfalls': 50,
 'Wayanad': 51,
 'Nagarhole National Park': 52,
 'Kanyakumari': 5

In [5]:
df.columns

Index(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys', 'description'],
      dtype='object')

In [6]:
df.drop(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys'], axis = 1, inplace = True)
df

description
0      The capital of India, Delhi is a cosmopolita...
1      Located on the banks of River Yamuna in Utta...
2      Lying on the western coast, Goa is India's s...
3      World's oldest living city, Varanasi - also ...
4      Shimla is the capital Himachal Pradesh in In...
5      Haridwar, considered to be among the seven h...
6      Nestled amidst Nilgiri hills, Ooty, also kno...
7      Jaipur is a vibrant amalgamation of the old ...
8      Situated in the Chittoor district of Andhra ...
9      Replete with picturesque shimmering beaches,...
10     Munnar is a popular hill-station of Kerala p...
11     The home of great saint Sai Baba, Shirdi is ...
12     Nestled in between the snow-capped slopes of...
13     Officially called Alappuzha, Alleppey is a c...
14     Somnath, literally meaning 'lord of the moon...
15     Ajanta and Ellora caves, considered to be on...
16     The gem of Uttarakhand - Nainital is a charm...
17     Home of the glorious Golden Temple, the icon...
18     Jaw-dropping locales, mesmerising sunrises, ...
19     Rameshwaram is one of the holiest places in ...
20     Pondicherry, officially known as Puducherry,...
21     Famously known as The City of Palaces, it wo...
22     Located in the foothills of the Himalayas al...
23     Puri in Odisha is one of the four must-visit...
24     Mumbai, the capital city of the Indian state...
25     Hampi, the city of ruins, is a UNESCO World ...
26     Located at a distance of 16km from Kottayam ...
27     Madurai, the cultural capital of Tamil Nadu,...
28     Located amidst imposing mountains in Karnata...
29     Udaipur, also known as the City of Lakes, is...
..                                                 ...
256    Nestled in the Shivaroy Hills of Tamil Nadu,...
257    Bhedaghat is known for the Dhuandar Falls (D...
258    Varkala is a coastal town in the southern pa...
259    Poovar is a small rustic town situated 27 km...
260    Located on the west of the Malabar coastline...
261    A treasure trove of natural wonders and hist...
262    The quaint town of Palakkad in central Keral...
263    Fondly known as Tellichery, Thalassery is a ...
264    With plenty of unexplored treasures, Nelliya...
265    62 kms off Kozhikode is Vythiri, a popular r...
266    Enriched with raw nature, a unique blend of ...
267    Kalpetta is a quaint town with a backdrop of...
268    Known to be the second largest wildlife sanc...
269    Located on the Malabar Coast of Kerala, Kann...
270    Located in Madhya Pradesh, the Buddhist monu...
271    Ujjain, considered to be one of the holiest ...
272    Known as the Capital of Andhra Pradesh, Amar...
273    Araku Valley is a comparatively unexplored h...
274    Set amid the Eastern Ghats, Ananthagiri Hill...
275    Nestled on the banks of River Krishna in the...
276    Endearingly known as the ‘Grand Canyon of In...
277    Anantapuram is the headquarters of Anantapur...
278    Known as the Land of Chillies, Guntur is fam...
279    A place of much historical value with beauti...
280    Nellore is a beautiful city lying on the ban...
281    Located on the banks of River Godavari in An...
282    Jagdalpur is a beautiful and naturally bount...
283    Dantewada recently came into being, in 1998,...
284    The capital of Chhattisgarh, Raipur is the l...
285    A culturally profound city, Bhilai is a plan...

[286 rows x 1 columns]

# Text Preprocessing

In [7]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [8]:
corpus = []
for i in range(len(df)):
    # Remove Hyperlinks
    destination = re.sub(r"http\S+", ' ', df['description'][i])
    
    # Remove Punctuation Marks and Special Symbols
    destination = re.sub('[^a-zA-Z0-9]', ' ', destination)
    
    # Lowercase
    destination = destination.lower()
    
    # Tokenization
    word_list = destination.split()
    
    # Remove Stopwords and perform Stemming / Lemmatization
    word_list = [wl.lemmatize(word, pos = 'v') for word in word_list if not word in stopwords.words('english')]    
    destination = ' '.join(word_list)
    corpus.append(destination)
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 27

In [9]:
corpus[0]

'capital india delhi cosmopolitan city historic old delhi modern new delhi historical monuments crowd shop malls extensive network modern metro system delhi university campus dilli multiple personalities consider city heart narrow wind lanes bylanes old delhi testament former mughal rule old delhi house one country oldest busiest market chandni chowk take time explore historical monuments red fort jama masjid humayun tomb purana qila want explore mughal history delhi famous temples scatter across city noteworthy ones akshardham temple lotus temple also know bahai temple iskon temple central delhi concentration country political power must visit place include rashtrapati bhawan raisina hill rajpath india gate best place visit area even build light see amar jawan jyoti india gate shin brightly people delhi love eat tourists find spoil choice multitude dish offer every corner every street kebabs tikkas chhole bhature delhi melt pot diverse culture fact reflect culinary palette city delhi 

In [10]:
df['Processed Text'] = corpus
df

description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is...   
..                                                 ...   
256    Nestled in the Shivaroy Hills of Tamil Nadu,...   
257    Bhedaghat is known for the Dhuandar Falls (D...   
258    Varkala is a coastal town in the southern pa...   
259    Poovar is a small rustic town situated 27 km...   
260    Located on the west of the Malabar coastline...   
261    A treasure trove of natural wonders and hist...   
262    The quaint town of Palakkad in central Keral...   
263    Fondly known as Tellichery, Thalassery is a ...   
264    With plenty of unexplored treasures, Nelliya...   
265    62 kms off Kozhikode is Vythiri, a popular r...   
266    Enriched with raw nature, a unique blend of ...   
267    Kalpetta is a quaint town with a backdrop of...   
268    Known to be the second largest wildlife sanc...   
269    Located on the Malabar Coast of Kerala, Kann...   
270    Located in Madhya Pradesh, the Buddhist monu...   
271    Ujjain, considered to be one of the holiest ...   
272    Known as the Capital of Andhra Pradesh, Amar...   
273    Araku Valley is a comparatively unexplored h...   
274    Set amid the Eastern Ghats, Ananthagiri Hill...   
275    Nestled on the banks of River Krishna in the...   
276    Endearingly known as the ‘Grand Canyon of In...   
277    Anantapuram is the headquarters of Anantapur...   
278    Known as the Land of Chillies, Guntur is fam...   
279    A place of much historical value with beauti...   
280    Nellore is a beautiful city lying on the ban...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        Processed Text  
0    capital india delhi cosmopolitan city historic...  
1    locate bank river yamuna uttar pradesh agra po...  
2    lie western coast goa india smallest state unl...  
3    world oldest live city varanasi also know kash...  
4    shimla capital himachal pradesh india popular ...  
5    haridwar consider among seven holiest cities i...  
6    nestle amidst nilgiri hill ooty also know 

# Text to Vector Conversion

In [11]:
# - Count Vectorizer
# - TFIDF Vectorizer
# - Hashing Vectorizer
# - Glove
# - FastText
# - Word2Vec
# - BERT
# ...
# ...
# ...

# Count Vectorizer

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
vectors_cv = cv.fit_transform(corpus)
df['vectors_cv'] = list(vectors_cv.toarray())
df

description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is...   
..                                                 ...   
256    Nestled in the Shivaroy Hills of Tamil Nadu,...   
257    Bhedaghat is known for the Dhuandar Falls (D...   
258    Varkala is a coastal town in the southern pa...   
259    Poovar is a small rustic town situated 27 km...   
260    Located on the west of the Malabar coastline...   
261    A treasure trove of natural wonders and hist...   
262    The quaint town of Palakkad in central Keral...   
263    Fondly known as Tellichery, Thalassery is a ...   
264    With plenty of unexplored treasures, Nelliya...   
265    62 kms off Kozhikode is Vythiri, a popular r...   
266    Enriched with raw nature, a unique blend of ...   
267    Kalpetta is a quaint town with a backdrop of...   
268    Known to be the second largest wildlife sanc...   
269    Located on the Malabar Coast of Kerala, Kann...   
270    Located in Madhya Pradesh, the Buddhist monu...   
271    Ujjain, considered to be one of the holiest ...   
272    Known as the Capital of Andhra Pradesh, Amar...   
273    Araku Valley is a comparatively unexplored h...   
274    Set amid the Eastern Ghats, Ananthagiri Hill...   
275    Nestled on the banks of River Krishna in the...   
276    Endearingly known as the ‘Grand Canyon of In...   
277    Anantapuram is the headquarters of Anantapur...   
278    Known as the Land of Chillies, Guntur is fam...   
279    A place of much historical value with beauti...   
280    Nellore is a beautiful city lying on the ban...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        Processed Text  \
0    capital india delhi cosmopolitan city historic...   
1    locate bank river yamuna uttar pradesh agra po...   
2    lie western coast goa india smallest state unl...   
3    world oldest live city varanasi also know kash...   
4    shimla capital himachal pradesh india popular ...   
5    haridwar consider among seven holiest cities i...   
6    nestle amidst nilgiri hill ooty als

# TFIDF Vectorizer

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer()
vectors_tv = tv.fit_transform(corpus)
df['vectors_tv'] = list(vectors_tv.toarray())
df

description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is...   
..                                                 ...   
256    Nestled in the Shivaroy Hills of Tamil Nadu,...   
257    Bhedaghat is known for the Dhuandar Falls (D...   
258    Varkala is a coastal town in the southern pa...   
259    Poovar is a small rustic town situated 27 km...   
260    Located on the west of the Malabar coastline...   
261    A treasure trove of natural wonders and hist...   
262    The quaint town of Palakkad in central Keral...   
263    Fondly known as Tellichery, Thalassery is a ...   
264    With plenty of unexplored treasures, Nelliya...   
265    62 kms off Kozhikode is Vythiri, a popular r...   
266    Enriched with raw nature, a unique blend of ...   
267    Kalpetta is a quaint town with a backdrop of...   
268    Known to be the second largest wildlife sanc...   
269    Located on the Malabar Coast of Kerala, Kann...   
270    Located in Madhya Pradesh, the Buddhist monu...   
271    Ujjain, considered to be one of the holiest ...   
272    Known as the Capital of Andhra Pradesh, Amar...   
273    Araku Valley is a comparatively unexplored h...   
274    Set amid the Eastern Ghats, Ananthagiri Hill...   
275    Nestled on the banks of River Krishna in the...   
276    Endearingly known as the ‘Grand Canyon of In...   
277    Anantapuram is the headquarters of Anantapur...   
278    Known as the Land of Chillies, Guntur is fam...   
279    A place of much historical value with beauti...   
280    Nellore is a beautiful city lying on the ban...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        Processed Text  \
0    capital india delhi cosmopolitan city historic...   
1    locate bank river yamuna uttar pradesh agra po...   
2    lie western coast goa india smallest state unl...   
3    world oldest live city varanasi also know kash...   
4    shimla capital himachal pradesh india popular ...   
5    haridwar consider among seven holiest cities i...   
6    nestle amidst nilgiri hill ooty als

# Hashing Vectorizer

In [14]:
from sklearn.feature_extraction.text import HashingVectorizer
hv = HashingVectorizer()
vectors_hv = hv.fit_transform(corpus)
df['vectors_hv'] = list(vectors_hv.toarray())
df

description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is...   
..                                                 ...   
256    Nestled in the Shivaroy Hills of Tamil Nadu,...   
257    Bhedaghat is known for the Dhuandar Falls (D...   
258    Varkala is a coastal town in the southern pa...   
259    Poovar is a small rustic town situated 27 km...   
260    Located on the west of the Malabar coastline...   
261    A treasure trove of natural wonders and hist...   
262    The quaint town of Palakkad in central Keral...   
263    Fondly known as Tellichery, Thalassery is a ...   
264    With plenty of unexplored treasures, Nelliya...   
265    62 kms off Kozhikode is Vythiri, a popular r...   
266    Enriched with raw nature, a unique blend of ...   
267    Kalpetta is a quaint town with a backdrop of...   
268    Known to be the second largest wildlife sanc...   
269    Located on the Malabar Coast of Kerala, Kann...   
270    Located in Madhya Pradesh, the Buddhist monu...   
271    Ujjain, considered to be one of the holiest ...   
272    Known as the Capital of Andhra Pradesh, Amar...   
273    Araku Valley is a comparatively unexplored h...   
274    Set amid the Eastern Ghats, Ananthagiri Hill...   
275    Nestled on the banks of River Krishna in the...   
276    Endearingly known as the ‘Grand Canyon of In...   
277    Anantapuram is the headquarters of Anantapur...   
278    Known as the Land of Chillies, Guntur is fam...   
279    A place of much historical value with beauti...   
280    Nellore is a beautiful city lying on the ban...   
281    Located on the banks of River Godavari in An...   
282    Jagdalpur is a beautiful and naturally bount...   
283    Dantewada recently came into being, in 1998,...   
284    The capital of Chhattisgarh, Raipur is the l...   
285    A culturally profound city, Bhilai is a plan...   

                                        Processed Text  \
0    capital india delhi cosmopolitan city historic...   
1    locate bank river yamuna uttar pradesh agra po...   
2    lie western coast goa india smallest state unl...   
3    world oldest live city varanasi also know kash...   
4    shimla capital himachal pradesh india popular ...   
5    haridwar consider among seven holiest cities i...   
6    nestle amidst nilgiri hill ooty als

# Version 1: Recommendations based on Recently Visited Destination

In [15]:
destination = 'Delhi City'
number_of_recommendations = 5

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(vectors_cv.toarray())
idx = destination_index_dict[destination]
similarity_list = similarity_matrix[idx]
lst = []
for i in range(len(similarity_list)):
    lst.append((similarity_list[i], i))
lst.sort(reverse = True)
recommendations = []
for i in range(len(lst)):
    recommendations.append(index_destination_dict[lst[i][1]])
recommendations.remove(destination)
recommendations[:number_of_recommendations]

['Trivandrum', 'Jaipur', 'Bhubaneswar', 'Hyderabad', 'Tirupati']

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('travel_destinations.csv')
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                                  Tags  \
0                        Historical & Heritage |  City   
1                        City |  Historical & Heritage   
2                                                 City   
3                                           Pilgrimage   
4                                         Hill Station   
5                                           Pilgrimage   
6                                         Hill Station   
7                        Historical & Heritage |  City   
8                                   Pilgrimage |  City   
9                                                Beach   
10                                        Hill Station   
11                                          Pilgrimage   
12                                        Hill Station   
13                           Beach |  Lake & Backwater   
14                                          Pilgrimage   
15                               Historical & Heritage   
16                                        Hill Station   
17                 Historical & Heritage |  Pilgrimage   
18                                        Hill Station   
19                                          Pilgrimage   
20                                       Beach |  City   
21                       Historical & Heritage |  City   
22                  Pilgrimage |  Adventure / Trekking   
23                                 Beach |  Pilgrimage   
24                       Historical & Heritage |  City   
25                               Historical & Heritage   
26                                    Lake & Backwater   
27         Historical & Heritage |  Pilgrimage |  City   
28                                        Hill Station   
29                               Historical & Heritage 

In [18]:
index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict

{0: 'Delhi City',
 1: 'Agra',
 2: 'Panjim',
 3: 'Varanasi',
 4: 'Shimla',
 5: 'Haridwar',
 6: 'Ooty',
 7: 'Jaipur',
 8: 'Tirupati',
 9: 'Andaman Islands',
 10: 'Munnar',
 11: 'Shirdi',
 12: 'Manali',
 13: 'Alleppey',
 14: 'Somnath',
 15: 'Ajanta Caves',
 16: 'Nainital',
 17: 'Amritsar',
 18: 'Darjeeling',
 19: 'Rameshwaram',
 20: 'Pondicherry',
 21: 'Mysore',
 22: 'Rishikesh',
 23: 'Puri',
 24: 'Mumbai',
 25: 'Hampi',
 26: 'Kumarakom',
 27: 'Madurai',
 28: 'Coorg',
 29: 'Udaipur',
 30: 'Kanchipuram',
 31: 'Jim Corbett National Park',
 32: 'Mussoorie',
 33: 'Hyderabad',
 34: 'Mahabaleshwar',
 35: 'Kovalam',
 36: 'Jodhpur',
 37: 'Ahmedabad',
 38: 'Kodaikanal',
 39: 'Thekkady',
 40: 'Khajuraho',
 41: 'Kaziranga National Park',
 42: 'Chikmagalur',
 43: 'Sabarimala',
 44: 'Konark',
 45: 'Gir National Park',
 46: 'Mahabalipuram',
 47: 'Gangtok',
 48: 'Jaisalmer',
 49: 'Bandhavgarh National Park',
 50: 'Athirapally Waterfalls',
 51: 'Wayanad',
 52: 'Nagarhole National Park',
 53: 'Kanyakumari

In [19]:
destination_index_dict = {}
for i in range(len(df)):
    destination_index_dict[df.loc[i]['City']] = i 
destination_index_dict

{'Delhi City': 0,
 'Agra': 1,
 'Panjim': 2,
 'Varanasi': 3,
 'Shimla': 4,
 'Haridwar': 5,
 'Ooty': 6,
 'Jaipur': 7,
 'Tirupati': 8,
 'Andaman Islands': 9,
 'Munnar': 10,
 'Shirdi': 11,
 'Manali': 12,
 'Alleppey': 13,
 'Somnath': 14,
 'Ajanta Caves': 15,
 'Nainital': 16,
 'Amritsar': 17,
 'Darjeeling': 18,
 'Rameshwaram': 19,
 'Pondicherry': 20,
 'Mysore': 21,
 'Rishikesh': 22,
 'Puri': 23,
 'Mumbai': 24,
 'Hampi': 25,
 'Kumarakom': 26,
 'Madurai': 27,
 'Coorg': 28,
 'Udaipur': 29,
 'Kanchipuram': 30,
 'Jim Corbett National Park': 31,
 'Mussoorie': 32,
 'Hyderabad': 33,
 'Mahabaleshwar': 34,
 'Kovalam': 35,
 'Jodhpur': 36,
 'Ahmedabad': 37,
 'Kodaikanal': 38,
 'Thekkady': 39,
 'Khajuraho': 40,
 'Kaziranga National Park': 41,
 'Chikmagalur': 42,
 'Sabarimala': 43,
 'Konark': 44,
 'Gir National Park': 45,
 'Mahabalipuram': 46,
 'Gangtok': 47,
 'Jaisalmer': 48,
 'Bandhavgarh National Park': 49,
 'Athirapally Waterfalls': 50,
 'Wayanad': 51,
 'Nagarhole National Park': 52,
 'Kanyakumari': 5

In [20]:
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                                  Tags  \
0                        Historical & Heritage |  City   
1                        City |  Historical & Heritage   
2                                                 City   
3                                           Pilgrimage   
4                                         Hill Station   
5                                           Pilgrimage   
6                                         Hill Station   
7                        Historical & Heritage |  City   
8                                   Pilgrimage |  City   
9                                                Beach   
10                                        Hill Station   
11                                          Pilgrimage   
12                                        Hill Station   
13                           Beach |  Lake & Backwater   
14                                          Pilgrimage   
15                               Historical & Heritage   
16                                        Hill Station   
17                 Historical & Heritage |  Pilgrimage   
18                                        Hill Station   
19                                          Pilgrimage   
20                                       Beach |  City   
21                       Historical & Heritage |  City   
22                  Pilgrimage |  Adventure / Trekking   
23                                 Beach |  Pilgrimage   
24                       Historical & Heritage |  City   
25                               Historical & Heritage   
26                                    Lake & Backwater   
27         Historical & Heritage |  Pilgrimage |  City   
28                                        Hill Station   
29                               Historical & Heritage 

In [21]:
df.columns

Index(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys', 'description'],
      dtype='object')

In [22]:
df.drop(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day','keys', 'description'], axis = 1, inplace = True)
df

historical & heritage  city  pilgrimage  hill station  beach  \
0                        1     1           0             0      0   
1                        1     1           0             0      0   
2                        0     1           0             0      0   
3                        0     0           1             0      0   
4                        0     0           0             1      0   
5                        0     0           1             0      0   
6                        0     0           0             1      0   
7                        1     1           0             0      0   
8                        0     1           1             0      0   
9                        0     0           0             0      1   
10                       0     0           0             1      0   
11                       0     0           1             0      0   
12                       0     0           0             1      0   
13                       0     0           0             0      1   
14                       0     0           1             0      0   
15                       1     0           0             0      0   
16                       0     0           0             1      0   
17                       1     0           1             0      0   
18                       0     0           0             1      0   
19                       0     0           1             0      0   
20                       0     1           0             0      1   
21                       1     1           0             0      0   
22                       0     0           1             0      0   
23                       0     0           1             0      1   
24                       1     1           0             0      0   
25                       1     0           0             0      0   
26                       0     0           0             0      0   
27                       1     1           1             0      0   
28                       0     0           0             1      0   
29                       1     0           0             0      0   
..                     ...   ...         ...           ...    ...   
256                      0     0           0             1      0   
257                      0     0           0             0      0   
258                      0     0           0             0      1   
259                      0     0           0             0      1   
260                      1     0           0             0      1   
261                      1     0           0             0      1   
262                      0     0           0             0      0   
263                      1     0           0             0      0   
264                      0     0           0             1      0   
265                      0     0           0             0      0   
266                      0     0           0             0      0   
267                      0     0           0             0      0   
268                      0     0           0             0      0   
269                      1     0           0             0      1   
270                      1     0           1             0      0   
271                      1     0           1             0      0   
272                      0     1           1             0      0   
273                      0     0           0             1      0   
274                      1     0           0             1      0   
275                      1     1           1             0      0   
276                      1     0           0             0      0   
277                      1     0           0             0      0   
278                      1     1           1             0      0   
279                      1     1           0             0      0   
280                      0     1           0             0      0   
281                      0     0           1             0      0   
282

In [23]:
destination_tags = df.values
destination_tags

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 0, 1]], dtype=int64)

In [24]:
destination_tags.shape

(286, 10)

In [25]:
from sklearn.metrics.pairwise import sigmoid_kernel
correlationMatrix = sigmoid_kernel(destination_tags, destination_tags)
print(correlationMatrix)

[[0.83365461 0.83365461 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 [0.83365461 0.83365461 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 [0.80049902 0.80049902 0.80049902 ... 0.76159416 0.80049902 0.80049902]
 ...
 [0.76159416 0.76159416 0.76159416 ... 0.80049902 0.80049902 0.80049902]
 [0.80049902 0.80049902 0.80049902 ... 0.80049902 0.88535165 0.83365461]
 [0.80049902 0.80049902 0.80049902 ... 0.80049902 0.83365461 0.83365461]]


In [26]:
# from sklearn.metrics.pairwise import cosine_similarity
# correlationMatrix = cosine_similarity(destination_tags, destination_tags)
# print(correlationMatrix)

In [27]:
correlationMatrix.shape

(286, 286)

# Recommendation based on Recently Visited Destination

In [28]:
def getRecommendations(destination_name):
    idx = destination_index_dict[destination_name]
    similarity_list = correlationMatrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i],i))
    return sorted(lst, reverse = True)

In [29]:
recommendations_list = getRecommendations('Shimla')
for element in recommendations_list[:10]:
    print(index_destination_dict[element[1]])

Ananthagiri Hills
Araku Valley
Nelliyampathy
Yercaud
Kaza
Dhanaulti
Guptakashi
Chamoli
Chail
Mashobra


# Recommendation based on free text-based query

In [30]:
df = pd.read_csv('travel_destinations.csv')
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                                  Tags  \
0                        Historical & Heritage |  City   
1                        City |  Historical & Heritage   
2                                                 City   
3                                           Pilgrimage   
4                                         Hill Station   
5                                           Pilgrimage   
6                                         Hill Station   
7                        Historical & Heritage |  City   
8                                   Pilgrimage |  City   
9                                                Beach   
10                                        Hill Station   
11                                          Pilgrimage   
12                                        Hill Station   
13                           Beach |  Lake & Backwater   
14                                          Pilgrimage   
15                               Historical & Heritage   
16                                        Hill Station   
17                 Historical & Heritage |  Pilgrimage   
18                                        Hill Station   
19                                          Pilgrimage   
20                                       Beach |  City   
21                       Historical & Heritage |  City   
22                  Pilgrimage |  Adventure / Trekking   
23                                 Beach |  Pilgrimage   
24                       Historical & Heritage |  City   
25                               Historical & Heritage   
26                                    Lake & Backwater   
27         Historical & Heritage |  Pilgrimage |  City   
28                                        Hill Station   
29                               Historical & Heritage 

In [31]:
df['description']

0        The capital of India, Delhi is a cosmopolita...
1        Located on the banks of River Yamuna in Utta...
2        Lying on the western coast, Goa is India's s...
3        World's oldest living city, Varanasi - also ...
4        Shimla is the capital Himachal Pradesh in In...
5        Haridwar, considered to be among the seven h...
6        Nestled amidst Nilgiri hills, Ooty, also kno...
7        Jaipur is a vibrant amalgamation of the old ...
8        Situated in the Chittoor district of Andhra ...
9        Replete with picturesque shimmering beaches,...
10       Munnar is a popular hill-station of Kerala p...
11       The home of great saint Sai Baba, Shirdi is ...
12       Nestled in between the snow-capped slopes of...
13       Officially called Alappuzha, Alleppey is a c...
14       Somnath, literally meaning 'lord of the moon...
15       Ajanta and Ellora caves, considered to be on...
16       The gem of Uttarakhand - Nainital is a charm...
17       Home of the glorious G

# Create corpus of processed text

In [32]:
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
wl = WordNetLemmatizer()

In [33]:
from nltk.corpus import stopwords
len(stopwords.words('english'))

179

In [34]:
corpus = []
for i in range(len(df)):
    #Remove Hyperlinks
    destination = re.sub(r"http\S+", ' ', df['description'][i])    
    #destination = re.sub(r'https?:\/\/\S*', '', df['description'][i], flags=re.MULTILINE)
    
    #Remove Punctuation Marks and Special Symbols
    destination = re.sub('[^a-zA-Z0-9]', ' ', destination)
    
    #Lowercase
    destination = destination.lower()
    
    #Create a list of strings using string.split() method
    destination = destination.split()
    
    # Prefer Lemmatization over Stemming
    #destination = [ps.stem(word) for word in destination if not word in stopwords.words('english')]
    destination = [wl.lemmatize(word, pos='v') for word in destination if not word in stopwords.words('english')]    
    destination = ' '.join(destination)
    corpus.append(destination)
    print(i, end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 27

In [35]:
df.columns

Index(['City', 'Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys', 'description'],
      dtype='object')

In [36]:
df.drop(['Tags', 'State', 'Old_age', 'Young_age', 'link 1',
       'Avg Expense Per Day', 'historical & heritage', 'city', 'pilgrimage',
       'hill station', 'beach', 'lake & backwater', 'adventure / trekking',
       'wildlife', 'waterfall', 'nature & scenic', 'keys'], axis = 1, inplace =True)
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                           description  
0      The capital of India, Delhi is a cosmopolita...  
1      Located on the banks of River Yamuna in Utta...  
2      Lying on the western coast, Goa is India's s...  
3      World's oldest living city, Varanasi - also ...  
4      Shimla is the capital Himachal Pradesh in In...  
5      Haridwar, considered to be among the seven h...  
6      Nestled amidst Nilgiri hills, Ooty, also kno...  
7      Jaipur is a vibrant amalgamation of the old ...  
8      Situated in the Chittoor district of Andhra ...  
9      Replete with picturesque shimmering beaches,...  
10     Munnar is a popular hill-station of Kerala p...  
11     The home of great saint Sai Baba, Shirdi is ...  
12     Nestled in between the snow-capped slopes of...  
13     Officially called Alappuzha, Alleppey is a c...  
14     Somnath, literally meaning 'lord of the moon...  
15     Ajanta and Ellora caves, considered to be on...  
16     The gem of Uttarakhand - Nainital is a charm...  
17     Home of the glorious Golden Temple, the icon...  
18     Jaw-dropping locales, mesmerising sunrises, ...  
19     Rameshwaram is one of the holiest places in ...  
20     Pondicherry, officially known as Puducherry,...  
21     Famously known as The City of Palaces, it wo...  
22     Located in the foothills of the Himalayas al...  
23     Puri in Odisha is one of the four must-visit...  
24     Mumbai, the capital city of the Indian state...  
25     Hampi, the city of ruins, is a UNESCO World ...  
26     Located at a distance of 16km from Kottayam ...  
27     Madurai, the cultural capital of Tamil Nadu,...  
28     Located amidst imposing mountains in Karnata...  
29     Udaipur, also known as the City of Lakes, is...  
..                          

In [37]:
df['processed_text'] = corpus
df.to_csv('destinations_with_processed_text.csv', index = False)

In [38]:
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                           description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is... 

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus)

In [40]:
X

<286x5563 sparse matrix of type '<class 'numpy.int64'>'
	with 22283 stored elements in Compressed Sparse Row format>

In [41]:
vectors = X.toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
df['vectors_cv'] = list(vectors)
df

City  \
0                     Delhi City   
1                           Agra   
2                         Panjim   
3                       Varanasi   
4                         Shimla   
5                       Haridwar   
6                           Ooty   
7                         Jaipur   
8                       Tirupati   
9                Andaman Islands   
10                        Munnar   
11                        Shirdi   
12                        Manali   
13                      Alleppey   
14                       Somnath   
15                  Ajanta Caves   
16                      Nainital   
17                      Amritsar   
18                    Darjeeling   
19                   Rameshwaram   
20                   Pondicherry   
21                        Mysore   
22                     Rishikesh   
23                          Puri   
24                        Mumbai   
25                         Hampi   
26                     Kumarakom   
27                       Madurai   
28                         Coorg   
29                       Udaipur   
..                           ...   
256                      Yercaud   
257                    Bhedaghat   
258                      Varkala   
259                       Poovar   
260                        Bekal   
261                       Kollam   
262                     Palakkad   
263                   Thalassery   
264                Nelliyampathy   
265                      Vythiri   
266                     Nilambur   
267                     Kalpetta   
268  Muthanga Wildlife Sanctuary   
269                       Kannur   
270                       Sanchi   
271                       Ujjain   
272                   Amaravathi   
273                 Araku Valley   
274            Ananthagiri Hills   
275                   Vijayawada   
276                    Gandikota   
277                    Anantapur   
278                       Guntur   
279                      Kurnool   
280                      Nellore   
281                  Rajahmundry   
282                    Jagdalpur   
283                    Dantewada   
284                       Raipur   
285                       Bhilai   

                                           description  \
0      The capital of India, Delhi is a cosmopolita...   
1      Located on the banks of River Yamuna in Utta...   
2      Lying on the western coast, Goa is India's s...   
3      World's oldest living city, Varanasi - also ...   
4      Shimla is the capital Himachal Pradesh in In...   
5      Haridwar, considered to be among the seven h...   
6      Nestled amidst Nilgiri hills, Ooty, also kno...   
7      Jaipur is a vibrant amalgamation of the old ...   
8      Situated in the Chittoor district of Andhra ...   
9      Replete with picturesque shimmering beaches,...   
10     Munnar is a popular hill-station of Kerala p...   
11     The home of great saint Sai Baba, Shirdi is ...   
12     Nestled in between the snow-capped slopes of...   
13     Officially called Alappuzha, Alleppey is a c...   
14     Somnath, literally meaning 'lord of the moon...   
15     Ajanta and Ellora caves, considered to be on...   
16     The gem of Uttarakhand - Nainital is a charm...   
17     Home of the glorious Golden Temple, the icon...   
18     Jaw-dropping locales, mesmerising sunrises, ...   
19     Rameshwaram is one of the holiest places in ...   
20     Pondicherry, officially known as Puducherry,...   
21     Famously known as The City of Palaces, it wo...   
22     Located in the foothills of the Himalayas al...   
23     Puri in Odisha is one of the four must-visit...   
24     Mumbai, the capital city of the Indian state...   
25     Hampi, the city of ruins, is a UNESCO World ...   
26     Located at a distance of 16km from Kottayam ...   
27     Madurai, the cultural capital of Tamil Nadu,...   
28     Located amidst imposing mountains in Karnata...   
29     Udaipur, also known as the City of Lakes, is... 

In [43]:
# from sklearn.feature_extraction.text import TfidfVectorizer
# tv = TfidfVectorizer()
# X_tv = tv.fit_transform(corpus)

In [44]:
# X_tv.toarray()

In [45]:
from sklearn.metrics.pairwise import sigmoid_kernel
correlationMatrix = sigmoid_kernel(vectors, vectors)
print(correlationMatrix)

[[0.78739282 0.76653193 0.76437332 ... 0.76309991 0.76697639 0.76504508]
 [0.76653193 0.78249379 0.76511962 ... 0.76294971 0.76578953 0.76362498]
 [0.76437332 0.76511962 0.80853216 ... 0.76227277 0.76690236 0.76392456]
 ...
 [0.76309991 0.76294971 0.76227277 ... 0.77384417 0.76347506 0.76234807]
 [0.76697639 0.76578953 0.76690236 ... 0.76347506 0.80060876 0.77174444]
 [0.76504508 0.76362498 0.76392456 ... 0.76234807 0.77174444 0.77585548]]


In [46]:
def getRecommendations(destination_name):
    idx = destination_index_dict[destination_name]
    similarity_list = correlationMatrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i],i))
    return sorted(lst, reverse = True)

In [47]:
recommendations_list = getRecommendations('Dachigam National Park')
for element in recommendations_list[:10]:
    print(index_destination_dict[element[1]])

Dachigam National Park
Kaziranga National Park
Jim Corbett National Park
Nagarhole National Park
Ranthambore National Park
Bandipur National Park
Sundarbans National Park
Manas National Park
Barpeta
Darjeeling


In [48]:
recommendations_list = getRecommendations('Araku Valley')
for element in recommendations_list[:10]:
    print(index_destination_dict[element[1]])

Araku Valley
Vizag
Darjeeling
Madikeri
Mussoorie
Narkanda
Lonavala
Aurangabad
Shillong
Manali


# Input a free text based query from the user

In [49]:
query = 'temple'

In [50]:
#Remove Hyperlinks
processed_query = re.sub(r"http\S+", ' ', query)    
#processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

#Remove Punctuation Marks and Special Symbols
processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

#Lowercase
processed_query = processed_query.lower()

#Create a list of strings using string.split() method
processed_query = processed_query.split()

# Prefer Lemmatization over Stemming
#processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
processed_query = ' '.join(processed_query)
# corpus.append(processed_query)
# print(i, end = ' ')

In [51]:
processed_query

'temple'

In [52]:
# corpus

In [53]:
new_corpus = []
for desc in corpus:
    new_corpus.append(desc)
new_corpus.append(processed_query)
new_corpus[0]

'capital india delhi cosmopolitan city historic old delhi modern new delhi historical monuments crowd shop malls extensive network modern metro system delhi university campus dilli multiple personalities consider city heart narrow wind lanes bylanes old delhi testament former mughal rule old delhi house one country oldest busiest market chandni chowk take time explore historical monuments red fort jama masjid humayun tomb purana qila want explore mughal history delhi famous temples scatter across city noteworthy ones akshardham temple lotus temple also know bahai temple iskon temple central delhi concentration country political power must visit place include rashtrapati bhawan raisina hill rajpath india gate best place visit area even build light see amar jawan jyoti india gate shin brightly people delhi love eat tourists find spoil choice multitude dish offer every corner every street kebabs tikkas chhole bhature delhi melt pot diverse culture fact reflect culinary palette city delhi 

In [54]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
new_X = cv.fit_transform(new_corpus)
new_vectors = new_X.toarray()

from sklearn.metrics.pairwise import sigmoid_kernel
new_correlationMatrix = sigmoid_kernel(new_vectors, new_vectors)
print(new_correlationMatrix)

[[0.78739282 0.76653193 0.76437332 ... 0.76697639 0.76504508 0.76189597]
 [0.76653193 0.78249379 0.76511962 ... 0.76578953 0.76362498 0.76159416]
 [0.76437332 0.76511962 0.80853216 ... 0.76690236 0.76392456 0.76159416]
 ...
 [0.76697639 0.76578953 0.76690236 ... 0.80060876 0.77174444 0.76159416]
 [0.76504508 0.76362498 0.76392456 ... 0.77174444 0.77585548 0.76159416]
 [0.76189597 0.76159416 0.76159416 ... 0.76159416 0.76159416 0.76166964]]


In [55]:
list_of_tuples = []
for i in range(len(df)):
    list_of_tuples.append((new_correlationMatrix[-1][i], i))
sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
for element in sorted_list_of_tuples[:10]:
    print(index_destination_dict[element[1]])

Tirupati
Badrinath
Trivandrum
Sabarimala
Guptakashi
Kanchipuram
Delhi City
Orchha
Aurangabad
Bhubaneswar


In [56]:
def getRecommendations_based_on_free_text_based_query(query, num):
    #Remove Hyperlinks
    processed_query = re.sub(r"http\S+", ' ', query)    
    #processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

    #Remove Punctuation Marks and Special Symbols
    processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

    #Lowercase
    processed_query = processed_query.lower()

    #Create a list of strings using string.split() method
    processed_query = processed_query.split()

    # Prefer Lemmatization over Stemming
    #processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
    processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
    processed_query = ' '.join(processed_query)
    # corpus.append(processed_query)
    # print(i, end = ' ')

    new_corpus = []
    for desc in corpus:
        new_corpus.append(desc)
    new_corpus.append(processed_query)
    #new_corpus

    from sklearn.feature_extraction.text import CountVectorizer
    cv = CountVectorizer()
    new_X = cv.fit_transform(new_corpus)
    new_vectors = new_X.toarray()
    
    from sklearn.metrics.pairwise import sigmoid_kernel
    new_correlationMatrix = sigmoid_kernel(new_vectors, new_vectors)
    #print(new_correlationMatrix)
    
    list_of_tuples = []
    for i in range(len(df)):
        list_of_tuples.append((new_correlationMatrix[-1][i], i))
    sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
    recommendation_list = []
    for element in sorted_list_of_tuples:
        recommendation_list.append(index_destination_dict[element[1]])
    return recommendation_list[:num]

In [57]:
query = 'wildlife'
final_recommendation_list = getRecommendations_based_on_free_text_based_query(query, 10)
for destination in final_recommendation_list:
    print(destination)

National Chambal Wildlife Sanctuary
Wayanad
Lunglei
Bandipur National Park
Raipur
Muthanga Wildlife Sanctuary
Gir National Park
Sambalpur
Kumily
Dudhwa National Park


In [58]:
def getRecommendations_based_on_free_text_based_query(query, num):
    #Remove HTML Tags
    processed_query = re.sub(r"http\S+", ' ', query)    
    #processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

    #Remove Punctuation Marks and Special Symbols
    processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

    #Lowercase
    processed_query = processed_query.lower()

    #Create a list of strings using string.split() method
    processed_query = processed_query.split()

    # Prefer Lemmatization over Stemming
    #processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
    processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
    processed_query = ' '.join(processed_query)
    # corpus.append(processed_query)
    # print(i, end = ' ')

    new_corpus = []
    for desc in corpus:
        new_corpus.append(desc)
    new_corpus.append(processed_query)
    #new_corpus

    from sklearn.feature_extraction.text import CountVectorizer
    cv = CountVectorizer()
    new_X = cv.fit_transform(new_corpus)
    new_vectors = new_X.toarray()
    
    list_of_tuples = []
    from numpy.linalg import norm
    for i in range(len(df)):
        cosine_similarity = np.dot(new_vectors[i], new_vectors[-1])/(norm(new_vectors[i])*norm(new_vectors[-1]))
        list_of_tuples.append((cosine_similarity, i))
    
    sorted_list_of_tuples = sorted(list_of_tuples, reverse = True)
    recommendation_list = []
    for element in sorted_list_of_tuples:
        recommendation_list.append(index_destination_dict[element[1]])
    return recommendation_list[:num]

In [59]:
query = 'sea'
final_recommendation_list = getRecommendations_based_on_free_text_based_query(query, 10)
for destination in final_recommendation_list:
    print(destination)

Alleppey
Dhanaulti
Kolukkumalai
Talasari Beach
Guptakashi
Harsil
Srisailam
Tirthal Valley
Sattal
Poovar


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import sigmoid_kernel
from pywebio.input import *
from pywebio.output import *
from IPython.display import Image
from IPython.display import display
import time
from pywebio.platform.flask import webio_view
from pywebio import STATIC_PATH
from flask import Flask, send_from_directory
app = Flask(__name__)

df = pd.read_csv('travel_destinations.csv')
cities = list(df['City'])
description = list(df['description'])

# Dictionary to map index to travel destination
index_destination_dict = {}
for i in range(len(df)):
    index_destination_dict[i] = df.loc[i]['City']
index_destination_dict

# Dictionary to map travel destination to index
destination_index_dict = {}
for i in range(len(df)):
    destination_index_dict[df.loc[i]['City']] = i
destination_index_dict

df1 = pd.read_csv('destinations_with_processed_text.csv')
corpus = df1['processed_text']


def previously_visited_destination(previously_visited_travel_destination):
    df2 = pd.read_csv('destinations_with_processed_text.csv')
    corpus = df2['processed_text']
    tv = TfidfVectorizer()
    X = tv.fit_transform(corpus)
    vectors = X.toarray()
    correlationMatrix = sigmoid_kernel(vectors, vectors)
    
    idx = destination_index_dict[str(previously_visited_travel_destination)]
    similarity_list = correlationMatrix[idx]
    lst = []
    for i in range(len(similarity_list)):
        lst.append((similarity_list[i], i))
    return sorted(lst, reverse = True)
    
def free_text_based_query():
    free_text = textarea('Enter a free text', rows = 3, placeholder = 'Write anything...\n\'snow winter nature trekking\' ... \'lake boating waterfall tiger\' ... \'market clothes nights history\' ... \'beach cruise camping boats ships\' ... \'temples hills altitude winter line\' ... \'lion safari forests camping nature\' ... ')
    number_of_recommendations = input("Enter the number of recommendations", type = NUMBER)
    
    #Remove Hyperlinks
    processed_query = re.sub(r"http\S+", ' ', str(free_text))   
    #processed_query = re.sub(r'https?:\/\/\S*', '', query, flags=re.MULTILINE)

    #Remove Punctuation Marks and Special Symbols
    processed_query = re.sub('[^a-zA-Z0-9]', ' ', processed_query)

    #Lowercase
    processed_query = processed_query.lower()

    #Create a list of strings using string.split() method
    processed_query = processed_query.split()
    
    wl = WordNetLemmatizer()
    # Prefer Lemmatization over Stemming
    #processed_query = [ps.stem(word) for word in processed_query if not word in stopwords.words('english')]
    processed_query = [wl.lemmatize(word, pos='v') for word in processed_query if not word in stopwords.words('english')]    
    processed_query = ' '.join(processed_query)
    # corpus.append(processed_query)
    # print(i, end = ' ')
    
    new_corpus = []
    for desc in corpus:
        new_corpus.append(desc)
    new_corpus.append(processed_query)
    #new_corpus
    
    from sklearn.feature_extraction.text import CountVectorizer
    cv = CountVectorizer()
    new_X = cv.fit_transform(new_corpus)
    new_vectors = new_X.toarray()
    
    from sklearn.metrics.pairwise import sigmoid_kernel
    new_correlationMatrix = sigmoid_kernel(new_vectors, new_vectors)
    #print(new_correlationMatrix)
    
    list_of_tuples = []
    for i in range(len(df)):
        list_of_tuples.append((new_correlationMatrix[-1][i], i))
    
    recommendation_list = []
    for element in sorted(list_of_tuples, reverse = True):
        recommendation_list.append(index_destination_dict[element[1]])
    final_rec = recommendation_list[:int(number_of_recommendations)]
    for rec in final_rec:
        put_html('<hr>')
        put_markdown("# *`%s`*" % rec)
        pic = 'DestinationPics/' + str(rec) + '.jpg'
        img = open(pic, 'rb').read()
        put_image(img, width='100%')
        

def select_recommendation_system():
    recommendation_system = select('Which type of recommendation system would you prefer?', ['Recommendation based on free text-based query', 'Recommendations similar to previously visited destination'])
    if(recommendation_system == 'Recommendation based on free text-based query'):
        free_text_based_query()
    if(recommendation_system == 'Recommendations similar to previously visited destination'):
        previously_visited_travel_destination = select('Select the previously visited travel destination', cities)
        recommendations_list = previously_visited_destination(previously_visited_travel_destination)
        number_of_recommendations = input("Enter the number of recommendations", type = NUMBER)
        for element in recommendations_list[:number_of_recommendations]:
            put_markdown("# *`%s`*" % index_destination_dict[element[1]])
            pic = 'DestinationPics/' + str(index_destination_dict[element[1]]) + '.jpg'
            img = open(pic, 'rb').read()
            put_image(img, width='100%')

def explore():
    put_markdown('## Please wait! Your request is being processed!')
    
    #Display Processbar
    put_processbar('bar');
    for i in range(1, 11):
        set_processbar('bar', i / 10)
        time.sleep(0.1)
        
    #Display the Travel Destination along with Description
    for i in range(len(df)):
        put_html('<hr>')
        put_markdown("# *`%s`*" % cities[i])
        pic = 'DestinationPics/' + str(cities[i]) + '.jpg'
        img = open(pic, 'rb').read()
        put_image(img, width='100%')
        #temp = description[i].replace('-', ' ')
        #put_text("     %s" % temp)
    put_markdown("# *In case of copyright issues, please drop an email to `abhinavsinha135@gmail.com`*")
    img = open('DestinationPics/India_1.jpg', 'rb').read()
    put_image(img, width='1500px')

def choices():
    img = open('DestinationPics/DesiSafar Logo.jpg', 'rb').read()
    put_image(img, width='900px')
    put_markdown('# **Travel Destination Recommendation System**')
    answer = radio("Choose one", options=['Explore Incredible India!', 'Get Travel Recommendations'])
    if(answer == 'Explore Incredible India!'):
        explore()
    if(answer == 'Get Travel Recommendations'):
        put_text('\nLet\'s get started! ')
        select_recommendation_system()

app.add_url_rule('/pywebio', 'webio_view', webio_view(choices), methods=['GET', 'POST', 'OPTIONS'])
app.run(host='localhost', port=80)
#app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://localhost:80/ (Press CTRL+C to quit)
127.0.0.1 - - [11/Aug/2023 12:31:52] "GET /pywebio HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:52] "GET /pywebio?app=index&ack=0 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:53] "GET /pywebio?app=index&ack=1 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:55] "GET /pywebio?app=index&ack=2 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:55] "GET /pywebio?app=index&ack=3 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:57] "GET /pywebio?app=index&ack=4 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:57] "GET /pywebio?app=index&ack=5 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:59] "GET /pywebio?app=index&ack=6 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:59] "POST /pywebio?app=index&ack=7 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:31:59] "GET /pywebio?app=index&ack=8 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:32:01] "GET /pywebio?app=index&ack=9 HTTP/1.1" 200 -
127.0.0.1 - - [11/Aug/2023 12:32:04] "GET /p